title: HUANG Yan
position: Ph.D. Student
affiliation: Your Affiliation
email: <a href="vlin03332@gmail.com">vlin03332@gmail.com</a>
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/huangyan211
linkedin: https://www.linkedin.com/
avatar: ./assets/img/profilephoto.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
