title: HUANG Yan
position: Postgraduate Student
affiliation: 
email: <a href="mailto:vlin03332@gmail.com">vlin03332@gmail.com</a>
keywords: HUANG Yan' academic personal homepage

avatar: ./assets/img/profilephoto.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant HUANG YAN for academic personal homepage.
canonical: https://huangyan211.github.io/HuangYan/
remote_theme: https://huangyan211.github.io/HuangYan
