title: HUANG Yan
position: Ph.D. Student
affiliation: Your Affiliation
email: <a href="mailto:vlin03332@gmail.com">vlin03332@gmail.com</a>
keywords: minimal academic

avatar: ./assets/img/profilephoto.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
